import { NextResponse } from "next/server";
import { z } from "zod";
import { generateText } from "@/lib/server/openai";
import { systemPrompts } from "@/lib/server/prompts";
import { extractJson } from "@/lib/server/json";
import { buildFallbackVideo } from "@/lib/server/fallbacks";
const schema = z.object({ story: z.object({ title: z.string(), summary: z.string().optional().default(""), description: z.string().optional().default("") }) });
function normalizeScript(script, story) { const fallback = buildFallbackVideo(story); const normalizedScenes = Array.isArray(script?.scenes) ? script.scenes.map((scene, index) => { if (typeof scene === "string") { return { title: `Scene ${index + 1}`, narration: scene, visual: "Animated chart and headline treatment", overlay: "Key caption overlay", duration: `${15 + index * 3}s` }; } return { title: scene?.title || `Scene ${index + 1}`, narration: scene?.narration || scene?.copy || scene?.text || fallback.scenes[index]?.narration || "Narration placeholder", visual: scene?.visual || fallback.scenes[index]?.visual || "Data-led motion visual", overlay: scene?.overlay || fallback.scenes[index]?.overlay || "Overlay title", duration: scene?.duration || fallback.scenes[index]?.duration || `${15 + index * 3}s` }; }) : fallback.scenes; return { ...fallback, ...script, estimatedDuration: script?.estimatedDuration || fallback.estimatedDuration, outputFormat: script?.outputFormat || fallback.outputFormat, scenes: normalizedScenes }; }
export async function POST(req) { try { const body = schema.parse(await req.json()); const aiText = await generateText({ instructions: systemPrompts.video, input: JSON.stringify(body) }); const rawScript = extractJson(aiText, buildFallbackVideo(body.story)); const script = normalizeScript(rawScript, body.story); return NextResponse.json({ success: true, script, aiPowered: Boolean(aiText) }); } catch (error) { return NextResponse.json({ success: false, message: error.message || "Failed to generate video script" }, { status: 500 }); } }
